
CREATE SCHEMA LATIHAN7;
USE LATIHAN7;
CREATE TABLE FAKULTAS (
	ID_FAKULTAS SMALLINT PRIMARY KEY,
	FAKULTAS VARCHAR(45)
)

CREATE TABLE JURUSAN (
	ID_JURUSAN SMALLINT PRIMARY KEY,
	ID_FAKULTAS SMALLINT,
	JURUSAN VARCHAR(45),
	FOREIGN KEY (ID_FAKULTAS) REFERENCES FAKULTAS(ID_FAKULTAS)
)

CREATE TABLE STRATA (
	ID_STRATA SMALLINT PRIMARY KEY,
	SINGKAT VARCHAR(10),
	STRATA VARCHAR(45)
)

CREATE TABLE PROGRAM_STUDI (
	ID_PROGRAM_STUDI SMALLINT PRIMARY KEY,
	ID_STRATA SMALLINT,
	ID_JURUSAN SMALLINT,
	PROGRAM_STUDI VARCHAR(60),
	FOREIGN KEY (ID_STRATA) REFERENCES STRATA(ID_STRATA),
	FOREIGN KEY (ID_JURUSAN) REFERENCES JURUSAN(ID_JURUSAN)
)

CREATE TABLE SELEKSI_MASUK (
	ID_SELEKSI_MASUK SMALLINT PRIMARY KEY,
	SINGKAT VARCHAR(12),
	SELEKSI_MASUK VARCHAR(45)
)


CREATE TABLE MAHASISWA (
	NIM VARCHAR(15) PRIMARY KEY,
	ID_SELEKSI_MASUK SMALLINT,
	ID_PROGRAM_STUDI SMALLINT,
	NAMA VARCHAR(45),
	ANGKATAN SMALLINT,
	TGL_LAHIR DATE,
	KOTA_LAHIR VARCHAR(60),
	JENIS_KELAMIN CHAR(1) CHECK (JENIS_KELAMIN IN ('P', 'L')),
	FOREIGN KEY (ID_SELEKSI_MASUK) REFERENCES SELEKSI_MASUK(ID_SELEKSI_MASUK),
	FOREIGN KEY (ID_PROGRAM_STUDI) REFERENCES PROGRAM_STUDI(ID_PROGRAM_STUDI)
)
ALTER TABLE SELEKSI_MASUK
MODIFY COLUMN SELEKSI_MASUK VARCHAR(100)

SELECT * FROM MAHASISWA;

INSERT INTO FAKULTAS (ID_FAKULTAS, FAKULTAS)
VALUES (1, 'EKONOMI & BISNIS');
INSERT INTO FAKULTAS (ID_FAKULTAS, FAKULTAS)
VALUES (2, 'ILMU KOMPUTER')

INSERT INTO JURUSAN (ID_JURUSAN, ID_FAKULTAS, JURUSAN)
VALUES (21, 2, 'INFORMATIKA')
INSERT INTO JURUSAN (ID_JURUSAN, ID_FAKULTAS, JURUSAN)
VALUES (22, 2, 'SISTEM INFORMASI')
INSERT INTO JURUSAN (ID_JURUSAN, ID_FAKULTAS, JURUSAN)
VALUES (23, 2, 'TEKNIK KOMPUTER')

INSERT INTO STRATA (ID_STRATA, SINGKAT, STRATA)
VALUES (1, 'D1', 'DIPLOMA')
INSERT INTO STRATA (ID_STRATA, SINGKAT, STRATA)
VALUES (2, 'S1', 'SARJANA')
INSERT INTO STRATA (ID_STRATA, SINGKAT, STRATA)
VALUES (3, 'S2', 'MAGISTER')

INSERT INTO PROGRAM_STUDI (ID_PROGRAM_STUDI, ID_STRATA, ID_JURUSAN, PROGRAM_STUDI)
VALUES (211, 2, 21, 'TEKNIK INFORMATIKA')
INSERT INTO PROGRAM_STUDI (ID_PROGRAM_STUDI, ID_STRATA, ID_JURUSAN, PROGRAM_STUDI)
VALUES (212, 2, 21, 'TEKNIK KOMPUTER')
INSERT INTO PROGRAM_STUDI (ID_PROGRAM_STUDI, ID_STRATA, ID_JURUSAN, PROGRAM_STUDI)
VALUES (219, 3, 21, 'MAGISTER ILMU KOMPUTER')

INSERT INTO SELEKSI_MASUK (ID_SELEKSI_MASUK, SINGKAT, SELEKSI_MASUK)
VALUES (1, 'SNMPTN', 'SELEKSI NASIONAL MAHASISWA PERGURUAN TINGGI NEGERI')
INSERT INTO SELEKSI_MASUK (ID_SELEKSI_MASUK, SINGKAT, SELEKSI_MASUK)
VALUES (2, 'SBMPTN', 'SELEKSI BERSAMA MAHASISWA PERGURUAN TINGGI NEGERI')

INSERT INTO MAHASISWA (NIM, ID_SELEKSI_MASUK, ID_PROGRAM_STUDI, NAMA, ANGKATAN, TGL_LAHIR, KOTA_LAHIR, JENIS_KELAMIN)
VALUES ('155150400', 1, 211, 'JONI', 2015, '1997-1-1', 'MALANG', 'L')
INSERT INTO MAHASISWA (NIM, ID_SELEKSI_MASUK, ID_PROGRAM_STUDI, NAMA, ANGKATAN, TGL_LAHIR, KOTA_LAHIR, JENIS_KELAMIN)
VALUES ('155150401', 2, 212, 'JON0', 2015, '1997-10-2', 'SITOBONDP', 'P')

UPDATE MAHASISWA
SET KOTA_LAHIR='SITUBONDO'
WHERE NIM='155150401'
UPDATE MAHASISWA
SET KOTA_LAHIR='PAPUA'
WHERE NIM='155150400'

DELETE FROM MAHASISWA
WHERE NIM='155150400'