CREATE DATABASE PENJUALANDVD;
-- 225150607111037-Hamdalla Agil Putra Nasol
USE PENJUALANDVD;

CREATE TABLE MOVIE (
	KODE_DVD VARCHAR(10) NOT NULL PRIMARY KEY,
	JUDUL VARCHAR(60) NOT NULL,
	HARGA_SEWA DOUBLE,
	DENDA DOUBLE,
	TAHUN_RILIS SMALLINT
)
	

CREATE TABLE GENRE_MOVIE (
	ID_GENRE SMALLINT NOT NULL,
	KODE_DVD VARCHAR(10) NOT NULL,
	FOREIGN KEY (ID_GENRE) REFERENCES GENRE (ID_GENRE),
	FOREIGN KEY (KODE_DVD) REFERENCES MOVIE (KODE_DVD)
)

CREATE TABLE GENRE (
	ID_GENRE SMALLINT NOT NULL PRIMARY KEY,
	GENRE VARCHAR(45) NOT NULL
)

CREATE TABLE TRANSAKSI (
	KODE_DVD VARCHAR(10) NOT NULL,
	KODE_PELANGGAN VARCHAR(10) NOT NULL,
	TANGGAL_SEWA DATE,
	PRIMARY KEY (KODE_DVD, KODE_PELANGGAN, TANGGAL_SEWA),
	TANGGAL_WAJIB_KEMBALI DATE,
	TANGGAL_REALISASI_KEMBALI DATE
)

CREATE TABLE PELANGGAN (
	KODE_PELANGGAN VARCHAR(10) NOT NULL PRIMARY KEY,
	ID_KELURAHAN SMALLINT NOT NULL,
	NAMA VARCHAR(45) NOT NULL,
	ALAMAT VARCHAR(60) NOT NULL,
	JENIS_KELAMIN CHAR(1) CHECK (JENIS_KELAMIN IN ('P', 'L')),
	FOREIGN KEY (ID_KELURAHAN) REFERENCES KELURAHAN (ID_KELURAHAN)
)


ALTER TABLE MOVIE
MODIFY COLUMN TAHUN_RILIS YEAR(4);

CREATE TABLE KONTAK_PELANGGAN (
	NO_HP VARCHAR(25) NOT NULL,
	KODE_PELANGGAN VARCHAR(10) NOT NULL,
	FOREIGN KEY (KODE_PELANGGAN) REFERENCES PELANGGAN (KODE_PELANGGAN)
)

ALTER TABLE KONTAK_PELANGGAN
ADD UNIQUE (NO_HP);

CREATE TABLE KECAMATAN (
	ID_KECAMATAN SMALLINT NOT NULL PRIMARY KEY,
	KECAMATAN VARCHAR(45)
)

CREATE TABLE KELURAHAN (
	ID_KELURAHAN SMALLINT NOT NULL PRIMARY KEY,
	ID_KECAMATAN SMALLINT NOT NULL,
	KELURAHAN VARCHAR(45) NOT NULL,
	FOREIGN KEY (ID_KECAMATAN) REFERENCES KECAMATAN (ID_KECAMATAN)
)

	
	

